<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>step05_ImageDiff</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>951f5cff-625d-4518-89e3-7cfcb11f0f53</testSuiteGuid>
   <testCaseLink>
      <guid>34f82087-fa8e-41f4-ac01-b0ea596467f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/StepByStep/step05_ImageDiff</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65232107-9fc4-4be1-941c-690aed0e6bad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85f876e3-b202-40a6-a863-27e1a105ab19</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
