<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dev_global-nav</name>
   <tag></tag>
   <elementGuidId>ea263611-595a-4c9d-a843-728390f8e5a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.global-nav</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
