<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_sidebar</name>
   <tag></tag>
   <elementGuidId>02c8eea1-3c9f-4908-9751-75244ec87da6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.sidebar</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
