<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_partners</name>
   <tag></tag>
   <elementGuidId>a70ff73b-e940-47e8-822b-a47888dc9732</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.partners</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
