<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_main-bnr</name>
   <tag></tag>
   <elementGuidId>84c0b1ce-d2b5-457c-837a-1c854639670b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.main-bnr</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
